version: '3.7'

services:
  postgres_db:
    container_name: boulder-postgres
    build: 
      context: ./BoulderPOS.postgres
      dockerfile: Dockerfile
    ports:
      - 4032:4032
    restart: always
  boulder-api:
    container_name: boulder-api
    build:
      context: ./BoulderPOS.api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres_db
    volumes:
      - ./BoulderPOS.API:/boulder-api/app
    ports:
      - 5000:80
  boulder-pos: 
    container_name: boulder-pos
    build:
      context: ./BoulderPOS.Client
      dockerfile: Dockerfile
    volumes: 
      - ./BoulderPOS.Client:/app
      - ./BoulderPOS.Client/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
  reverse-proxy:
    image: nginx:stable-alpine
    container_name: reverse-proxy
    depends_on: 
      - boulder-waiver
      - boulder-api
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  