// <auto-generated />
using System;
using BoulderPOS.API.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BoulderPOS.API.Migrations
{
    [DbContext(typeof(POSDBContext))]
    partial class POSDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BoulderPOS.API.Models.CustomerEntries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customerId");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<bool>("UnlimitedEntries")
                        .HasColumnType("boolean")
                        .HasColumnName("unlimitedEntries");

                    b.Property<DateTime>("Updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pK_customerEntries");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("iX_customerEntries_customerId");

                    b.ToTable("customerEntries");
                });

            modelBuilder.Entity("BoulderPOS.API.Models.CustomerSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("AutoRenewal")
                        .HasColumnType("boolean")
                        .HasColumnName("autoRenewal");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customerId");

                    b.Property<DateTime>("Updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("date")
                        .HasColumnName("endDate");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("date")
                        .HasColumnName("startDate");

                    b.HasKey("Id")
                        .HasName("pK_customerSubscription");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("iX_customerSubscription_customerId");

                    b.ToTable("customerSubscription");
                });

            modelBuilder.Entity("BoulderPOS.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("categoryId");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("Updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pK_product");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("iX_product_categoryId");

                    b.ToTable("product");
                });

            modelBuilder.Entity("BoulderPOS.API.Models.ProductPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customerId");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("productId");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("sellingPrice");

                    b.Property<DateTime>("Updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("boolean")
                        .HasColumnName("isRefunded");

                    b.HasKey("Id")
                        .HasName("pK_productPayment");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("iX_productPayment_customerId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("iX_productPayment_productId");

                    b.ToTable("productPayment");
                });

            modelBuilder.Entity("BoulderPOS.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birthDate");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lastName");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("phoneNumber");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("bytea")
                        .HasColumnName("picture");

                    b.Property<DateTime>("Updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pK_user");

                    b.ToTable("user");
                });

            modelBuilder.Entity("BoulderPOS.Model.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("CategoryIcon")
                        .HasColumnType("bytea")
                        .HasColumnName("categoryIcon");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pK_productCategory");

                    b.ToTable("productCategory");
                });

            modelBuilder.Entity("BoulderPOS.API.Models.CustomerEntries", b =>
                {
                    b.HasOne("BoulderPOS.Model.Customer", "Customer")
                        .WithOne("Entries")
                        .HasForeignKey("BoulderPOS.API.Models.CustomerEntries", "CustomerId")
                        .HasConstraintName("fK_customerEntries_user_customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BoulderPOS.API.Models.CustomerSubscription", b =>
                {
                    b.HasOne("BoulderPOS.Model.Customer", "customer")
                        .WithOne("Subscription")
                        .HasForeignKey("BoulderPOS.API.Models.CustomerSubscription", "CustomerId")
                        .HasConstraintName("fK_customerSubscription_user_customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("BoulderPOS.API.Models.Product", b =>
                {
                    b.HasOne("BoulderPOS.Model.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fK_product_productCategory_categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BoulderPOS.API.Models.ProductPayment", b =>
                {
                    b.HasOne("BoulderPOS.Model.Customer", "User")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("fK_productPayment_user_customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoulderPOS.API.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fK_productPayment_product_productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BoulderPOS.API.Models.Product", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BoulderPOS.Model.Customer", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Orders");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("BoulderPOS.Model.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
